- name: variables from inventory
  hosts: local
  connection: local
  tasks:
  - name: fetch variables from inventory file
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, duration is {{ DURATION }} and trainer is {{ TRAINER }}"