- name: Host level variables from inventory
  hosts: frontend
  tasks:
  - name: Fetch varibles from inventory Host
    ansible.builtin.debug:
      msg: "{{frontend.inventory}} Course is {{ COURSE }}, duration is {{ DURATION }} and the trainer {{ TRAINER }}"