- name: Datatypes Demonstration
  hosts: local
  connection: local
  vars:
   COURSE: "DevSecOps with AWS" #String
   DURATION: 130 #number
   IS_LIVE: true #boolean
   TOOLS: #List []
    - LINUX 
    - Shell
    - Ansible
   CONCEPT: #map/dictionary/object
    CI: Jenkins
    SCRIPTING: "Shell, Ansible, Terraform, Python"
  tasks:
  - name: Datatypes Demo
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, is live: {{ IS_LIVE }} tools are: {{ TOOLS }} and the concept is {{ CONCEPT }}"
  