- name: ansible use gathering facts
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx when redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when ansible_os_family == "RedHat"
  
  - name: install nginx when debian
    ansible.builtin.apt:
      ansible: nginx
      state: present
    when ansible_os_family = "Debian"