- name: loops in ansible
  hosts: local
  connection: local
  taks:
   - name: print names in a loops
     ansible.builtin.debug:
      msg: "{{ item }}" # item is a reserved word in ansible iterate over a loop
     loop:
       - Surekha
       - Sunil
       - Sam
       - Saran

    